src/Entity/Salida.php
<?php

namespace App\Entity;

use App\Repository\SalidaRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SalidaRepository::class)]
class Salida
{

    const FICHAJE_EXITOSO = '¡Has terminado tu jornada laboral!';

    const TYPES = [
        'Talent Garden - Madrid' => 'Madrid',
        'Factoría F5 - Barcelona' => 'Barcelona',
        'Teletrabajo' => 'Teletrabajo'
    ];

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $fecha_publicacion = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $comentario = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $locacion = null;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'salida')]
    private $user;

    /**
     * Salida constructor.
     */
    public function __construct()
    {
        $this->fecha_publicacion = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFechaPublicacion(): ?\DateTimeInterface
    {
        return $this->fecha_publicacion;
    }

    public function setFechaPublicacion(\DateTimeInterface $fecha_publicacion): self
    {
        $this->fecha_publicacion = $fecha_publicacion;

        return $this;
    }

    public function getComentario(): ?string
    {
        return $this->comentario;
    }

    public function setComentario(?string $comentario): self
    {
        $this->comentario = $comentario;

        return $this;
    }

    public function getLocacion(): ?string
    {
        return $this->locacion;
    }

    public function setLocacion(?string $locacion): self
    {
        $this->locacion = $locacion;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param mixed $user
     */
    public function setUser($user): void
    {
        $this->user = $user;
    }
}

src/Form/SalidaType.php
<?php

namespace App\Form;

use App\Entity\Salida;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\CallbackTransformer;

class SalidaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('locacion', ChoiceType::class, [
                'choices'  => Salida::TYPES
            ])
            ->add('comentario')
            ->add('FINALIZAR', SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Salida::class,
        ]);
    }
}

src/Controller/SalidaController.php
<?php

namespace App\Controller;

use App\Entity\Salida;
use App\Form\SalidaType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Persistence\ManagerRegistry;
use Knp\Component\Pager\PaginatorInterface;

class SalidaController extends AbstractController
{
    #[Route('/salida', name: 'app_salida')]
    public function index(Request $request, ManagerRegistry $doctrine): Response
    {
        $salida = new Salida();
        $form = $this->createForm(SalidaType::class, $salida);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $user = $this->getUser();
            $salida->setUser($user);
            $em = $doctrine->getManager();
            $em->persist($salida);
            $em->flush();
            $this->addFlash('exito', Salida::FICHAJE_EXITOSO);
            return $this->redirectToRoute('app_salida');
        }
        return $this->render('salida/index.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route('/salida/{id}', name: 'verSalida')]
    public function VerSalida($id, Request $request, ManagerRegistry $doctrine)
    {
        $em = $doctrine->getManager();
        $salida = $em->getRepository(Salida::class)->find($id);
        return $this->render('salida/verSalida.html.twig', ['salida' => $salida]);
    }

    #[Route('/mis-salidas', name: 'misSalidas')]
    public function MisSalidas(ManagerRegistry $doctrine)
    {
        $em = $doctrine->getManager();
        $user = $this->getUser();
        $salidas = $em->getRepository(Salida::class)->findBy(['user' => $user]);
        return $this->render('salida/misSalidas.html.twig', ['salidas' => $salidas]);
    }

    #[Route('/todossalida', name: 'todosSalida')]
    public function TodosSalida(PaginatorInterface $paginator, Request $request, ManagerRegistry $doctrine)
    {
        $user = $this->getUser(); //OBTENGO AL USUARIO ACTUALMENTE LOGUEADO
        if ($user) {
            $em = $doctrine->getManager();
            $query = $em->getRepository(Salida::class)->BuscarTodasLasSalidas();
            $pagination = $paginator->paginate(
                $query, /* query NOT result */
                $request->query->getInt('page', 1), /*page number*/
                10 /*limit per page*/
            );
            return $this->render('salida/todossalida.html.twig', [
                'pagination' => $pagination
            ]);
        } else {
            return $this->redirectToRoute('app_login');
        }
    }
}

templates/salida/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
{{parent()}} -Fichaje de salida{% endblock %}

{% block body %}
    {{ parent() }}
    <div class="container h-100 ">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-10 bg-white rounded my-3 p-5">
            <center>
                <h1>Registrar Fichaje de Salida</h1>
                {% for message in app.flashes('exito') %}
                    <div class="alert alert-success">
                {{ message }}
                    </div>
                {% endfor %}
                {{form(form)}}
            </center>
            </div>
        </div>
    </div>

{% endblock %}

templates/salida/misSalidas.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{parent()}} - Mis Salidas{% endblock %}

{% block body %}
    {{ parent() }}
    <div class="container">
        <div class="row" style="justify-content: center; margin-top: 20px">
            <div class="col-md-6">
            <h2 style="color: white; text-align: center">Mis Salidas</h2>
                {% for salida in salidas %}
                    <div class="bg-white rounded p-3 my-3" onclick="window.location.href='{{ path('verSalida',{id:salida.id}) }}'" style="cursor: pointer">
                        <h6>{{ salida.user.firstName }} - Fichaje de Salida</h6>
                        <div class=" bg-green"><i class="far fa-clock"></i><strong> Fecha: {{ salida.fechaPublicacion | date }} </strong></div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/salida/todosSalida.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{parent()}} - Todos Salida {% endblock %}

{% block body %}
     {{ parent() }}
    <div class="container">
        <div class="row" style="justify-content: center; margin-top: 20px">
            <div class="col-md-8">
            <h3 style="color: white; text-align: center">Fichaje de Salida de los Empleados</h3>
            {% for salida in pagination %}
                <div class="bg-white rounded p-3 my-3 cursor"  onclick="window.location.href='{{ path('verSalida',{id:salida.id}) }}'">
                    <div class="d-flex bd-highlight">
                        <div class="p-2 flex-grow-1 bd-highlight">
                             <h6>Fichaje de Salida de {{salida.firstname}}</h6>
                             <div class="bg-yellow"> <i class="fa fa-user"></i><strong> Sede {{salida.locacion}}</strong></div>
                             <div class=" bg-green"><i class="far fa-clock"></i>Fecha: {{ salida.fecha_publicacion | date }}</div>
                        </div>
                            <div class="text-justify my-3">
                                {{ salida.comentario }}
                            </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
     <div class="d-flex justify-content-center">
         <div class="navigation">
             {{ knp_pagination_render(pagination) }}
         </div>

{% endblock %}

templates/salida/verSalida.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{parent()}} - ver salida {% endblock %}

{% block body %}
    {{ parent() }}
    <div class="container bg-white rounded my-3 p-4 col-md-6">
        <div class="d-flex bd-highlight">
            <div class="p-2 flex-grow-1 bd-highlight">
                <h3>{{salida.user.firstName}} - Fichaje de Salida</h3>
                <div class="my-3" style="color:#3282b8;">
                  <i class="fa fa-thumbs-up"></i><strong>
                </div>
                <div style="color:#5957a1;"> 
                    <i class="far fa-clock"></i> <strong>Fecha: {{ salida.fechaPublicacion | date }}</strong>
                </div>
            </div>
        <hr>
        <div class="text-justify my-3">
            Comentario: {{ salida.comentario }}
        </div>
      </div>
{% endblock %}